---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blobfuse-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: blobfusecreds
    options:
      container: CONTAINER-NAME
      tmppath: /mnt/blobfuse01  # make sure it's unique for every blobfuse PV
      mountoptions: "--file-cache-timeout-in-seconds=120"
